version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    depends_on:
      - db

  db:
    image: library/mysql:8.0.26
    platform: linux/x86_64
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      db_url: mysql://mysql:mysql@db:3306/mysql
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_ROOT_HOST: '%'
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - 3306:3306

  redis:
    image: redis:latest

volumes:
  mysql_data: